fail_fast: true
repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Autoflake
        entry: poetry run autoflake --in-place --remove-unused-variables --recursive 
        pass_filenames: true
        language: system
        types_or: [
          python,
        ]
      - id: black
        name: Black
        entry: poetry run black src
        pass_filenames: false
        language: system
        types_or: [
          python,
        ]
      - id: isort
        name: isort
        entry: poetry run isort 
        pass_filenames: true
        language: system
        types_or: [
          python,
        ]
      - id: mypy
        name: MyPy
        entry: poetry run mypy src --warn-unused-ignores
        pass_filenames: false
        language: system
        types_or: [
          python,
          jupyter
        ]
        verbose: true
      - id: pylint
        name: Pylint
        entry: poetry run pylint --enable useless-suppression
        always_run: true
        pass_filenames: true 
        language: system
        types_or: [
          python,
        ]
        verbose: true